# .github/workflows/rubocop-todo-regenerator.yml
name: rubocop-todo
on:
  schedule:
    - cron: "0 6 * * WED"
  workflow_dispatch:
jobs:
  docker-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: e621
  rubocop-todo:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/prepare-docker-image
      - name: Generate rubocop TODOs
        run: $DOCKER_RUN rubocop --auto-gen-config --auto-gen-only-exclude --exclude-limit 20000
